name: Keep SpringBoot Alive

permissions:
  contents: read

on:
  schedule:
    - cron: "*/14 * * * *" # Every 14 minutes
  workflow_dispatch:

jobs:
  ping_health:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server & Database
        run: curl -I --max-time 10 https://admission-consulting-system.onrender.com/career-service/health
